"use client";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

import { Terminal } from "lucide-react";
import { useState } from "react";

export default function Page() {
  const [showAlert, setShowAlert] = useState(false)

  const handleClick = () => {
    setShowAlert(!showAlert)
  };

  return (
    <div className="flex flex-col gap-8 min-h-svh items-center justify-center">
      <div className="flex flex-col items-center gap-2">
        <h1 className="text-2xl font-bold">
          Next + Shadcn + Tailwind = Generated by v0
        </h1>
        <div className="text-sm">
          Get started by editing{" "}
          <code className="rounded bg-black/[.05] px-1 py-0.5 font-semibold dark:bg-white/[.06]">
            app/page.tsx asasda
          </code>
        </div>
        <div className="flex gap-2 mt-2">
          <Button size="sm" variant="secondary" onClick={handleClick}>
            Cancel
          </Button>
          <Button size="sm" onClick={handleClick}>
            Submit
          </Button>
        </div>
      </div>
      {showAlert && <Alert className="w-96" variant="destructive">
        <Terminal className="h-4 w-4" />
        <AlertTitle>Heads up!</AlertTitle>
        <AlertDescription>
          You can add components and dependencies to your app using the cli.
        </AlertDescription>
      </Alert>} 
    </div>
  );
}
